//! Metadati per frame (README §72).
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FrameMetadata {
    pub frame_id: String,
    pub camera_id: String,
    pub exposure_requested_ns: u64,
    pub exposure_reported_ns: Option<u64>,
    pub sensitivity_requested: u32,
    pub sensitivity_reported: Option<u32>,
    pub timestamp_ns: u64,
    pub physical_camera_id: Option<String>,
    pub request_id: Option<u32>,
    pub sequence_id: Option<String>,
    pub frame_number: Option<u64>,
    /// UTC acquisition time; timestamp_ns remains the device's monotonic sensor clock.
    pub received_at_unix_ns: Option<u64>,
    pub clock_offset_ns: Option<i64>,
    pub clock_uncertainty_ns: Option<u64>,
    pub width: Option<u32>,
    pub height: Option<u32>,
    pub pixel_format: Option<String>,
    pub row_stride_bytes: Option<u32>,
    pub bits_per_sample: Option<u8>,
    pub byte_order: Option<String>,
    pub cfa_pattern: Option<String>,
    pub black_levels: Option<[f64; 4]>,
    pub white_level: Option<u32>,
    pub active_area: Option<[u32; 4]>,
    pub color_matrix: Option<[f64; 9]>,
    pub calibration_illuminant: Option<u16>,
    pub frame_duration_requested_ns: Option<u64>,
    pub frame_duration_reported_ns: Option<u64>,
    pub focus_requested_diopters: Option<f64>,
    pub focus_reported_diopters: Option<f64>,
    pub focus_mode: Option<String>,
    pub white_balance_mode: Option<String>,
    pub white_balance_gains: Option<[f64; 4]>,
    pub white_balance_transform: Option<[f64; 9]>,
    pub crop_region: Option<[u32; 4]>,
    pub zoom_requested: Option<f64>,
    pub zoom_reported: Option<f64>,
    pub ois_mode: Option<String>,
    pub processing_modes: std::collections::BTreeMap<String, String>,
    pub sensor_temperature_c: Option<f64>,
    pub device_temperature_c: Option<f64>,
    pub orientation_degrees: Option<u16>,
    pub calibration_kind: Option<String>,
    pub app_version: Option<String>,
    pub protocol_version: Option<String>,
    pub android_version: Option<String>,
    pub config_version: Option<u32>,
    pub warnings: Vec<String>,
    /// Preserve vendor capture results without interpreting unknown keys.
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}
